import CryptoKit
import Foundation
import PathnodChallengeCore
import XCTest

final class ChallengeCoreTests: XCTestCase {
    private let key = Curve25519.Signing.PrivateKey()

    private func hexData(_ hex: String) -> Data {
        Data(stride(from: 0, to: hex.count, by: 2).map {
            UInt8(hex.dropFirst($0).prefix(2), radix: 16)!
        })
    }

    private func infoData() -> Data {
        var data = Data([0, 1])
        data.append(key.publicKey.rawRepresentation)
        data.append(Data(repeating: 0, count: 36))
        return data
    }

    private func signedResponse(
        challenge: DeviceProtocolV0.Challenge,
        timestamp: UInt64 = 42,
        counter: UInt32
    ) throws -> Data {
        var message = Data("Pathnod/challenge/v0".utf8)
        message.append(challenge.wireData())
        message.append(contentsOf: bytes(timestamp))
        message.append(contentsOf: bytes(counter))
        message.append(Data(repeating: 0, count: 32))
        let signature = try key.signature(for: Data(SHA256.hash(data: message)))
        var response = signature
        response.append(contentsOf: bytes(timestamp))
        response.append(contentsOf: bytes(counter))
        response.append(contentsOf: [0, 0])
        XCTAssertEqual(DeviceProtocolV0.signedMessage(
            challenge: challenge, response: try DeviceProtocolV0.Response(wireData: response)
        ), message)
        return response
    }

    private func bytes<T: FixedWidthInteger>(_ value: T) -> [UInt8] {
        stride(from: T.bitWidth - 8, through: 0, by: -8).map {
            UInt8(truncatingIfNeeded: value >> $0)
        }
    }

    func testInfoValidationAndCanonicalChallenge() throws {
        let info = try DeviceProtocolV0.Info(wireData: infoData())
        XCTAssertEqual(info.publicKey, key.publicKey.rawRepresentation)
        XCTAssertEqual(info.capabilities, 0)
        XCTAssertEqual(info.protocolHint, Data(repeating: 0, count: 32))
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(0..<32), observationEpoch: 0x01020304,
            observationHint: Data(0xa0..<0xa8)
        )
        XCTAssertEqual(challenge.wireData().count, 44)
        XCTAssertEqual(Array(challenge.wireData()[32..<36]), [1, 2, 3, 4])
        XCTAssertEqual(DeviceProtocolV0.domain.count, 20)

        XCTAssertThrowsError(try DeviceProtocolV0.Info(wireData: infoData().dropLast()))
        var wrongVersion = infoData()
        wrongVersion[0] = 1
        XCTAssertThrowsError(try DeviceProtocolV0.Info(wireData: wrongVersion)) {
            XCTAssertEqual($0 as? DeviceProtocolV0.ProtocolError, .unsupportedDevice)
        }
        XCTAssertThrowsError(try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 0, count: 31), observationEpoch: 0,
            observationHint: Data(repeating: 0, count: 8)
        ))
    }

    func testDEV09InteroperabilityVector() throws {
        // Public interoperability vector generated by DEV-09.
        let info = try DeviceProtocolV0.Info(wireData: hexData(
            "0001ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c" +
            "000000000000000000000000000000000000000000000000000000000000000000000000"
        ))
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(0..<32), observationEpoch: 0,
            observationHint: Data(repeating: 0, count: 8)
        )
        let response = try DeviceProtocolV0.Response(wireData: hexData(
            "bb9541f0b1b8d273b230f1c7accbe941fbfb43cfedcc934486b0bd4feeb3e07" +
            "4470663c7bb14e4fae6411e0b40c2a95dce2421f42ae35d98df1fd188521b080e" +
            "000000000000002a000000010000"
        ))
        XCTAssertEqual(response.deviceTimestamp, 42)
        XCTAssertEqual(response.deviceCounter, 1)
        XCTAssertNoThrow(try DeviceProtocolV0.verify(
            response: response, challenge: challenge, info: info
        ))
    }

    func testResponseRejectsTruncationAndUnsupportedEvidence() throws {
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 1, count: 32), observationEpoch: 2,
            observationHint: Data(repeating: 3, count: 8)
        )
        let response = try signedResponse(challenge: challenge, counter: 1)
        XCTAssertEqual(response.count, 78)
        XCTAssertThrowsError(try DeviceProtocolV0.Response(wireData: response.dropLast()))
        var extra = response
        extra.append(9)
        XCTAssertThrowsError(try DeviceProtocolV0.Response(wireData: extra))
        extra[77] = 1
        XCTAssertThrowsError(try DeviceProtocolV0.Response(wireData: extra)) {
            XCTAssertEqual($0 as? DeviceProtocolV0.ProtocolError, .unsupportedEvidence)
        }
    }

    func testThreeSequentialVerifiedChallengesAndMedian() throws {
        var session = ChallengeSession(info: try .init(wireData: infoData()))
        for attempt in 1...3 {
            let nonce = Data(repeating: UInt8(attempt), count: 32)
            let wire = try session.beginChallenge(
                nonce: nonce, observationEpoch: 2,
                observationHint: Data(repeating: 0, count: 8),
                startedAt: Double(attempt)
            )
            XCTAssertEqual(wire.count, 44)
            let challenge = try DeviceProtocolV0.Challenge(
                nonce: nonce, observationEpoch: 2,
                observationHint: Data(repeating: 0, count: 8)
            )
            let response = try signedResponse(challenge: challenge, counter: UInt32(attempt))
            guard case let .verified(result) = try session.receive(
                response, at: Double(attempt) + Double(attempt) / 100,
                via: .notification
            ) else { return XCTFail("Expected a verified response") }
            XCTAssertEqual(result.attempt, attempt)
            XCTAssertEqual(result.roundTripMilliseconds, Double(attempt * 10), accuracy: 0.001)
        }
        XCTAssertTrue(session.isComplete)
        XCTAssertEqual(session.medianNotificationRTTMilliseconds!, 20, accuracy: 0.001)
        XCTAssertThrowsError(try session.beginChallenge(
            nonce: Data(repeating: 4, count: 32), observationEpoch: 2,
            observationHint: Data(repeating: 0, count: 8), startedAt: 4
        ))
    }

    func testStaleDuplicateAndMismatchedResponse() throws {
        var session = ChallengeSession(info: try .init(wireData: infoData()))
        let hint = Data(repeating: 0, count: 8)
        let first = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 1, count: 32), observationEpoch: 2,
            observationHint: hint
        )
        _ = try session.beginChallenge(nonce: first.nonce, observationEpoch: 2,
                                       observationHint: hint, startedAt: 1)
        let oldResponse = try signedResponse(challenge: first, counter: 1)
        _ = try session.receive(oldResponse, at: 1.1, via: .notification)

        let second = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 2, count: 32), observationEpoch: 2,
            observationHint: hint
        )
        _ = try session.beginChallenge(nonce: second.nonce, observationEpoch: 2,
                                       observationHint: hint, startedAt: 2)
        guard case .ignoredDuplicate = try session.receive(
            oldResponse, at: 2.01, via: .notification
        ) else { return XCTFail("Old response must be ignored") }
        XCTAssertEqual(session.results.count, 1)
        XCTAssertThrowsError(try session.receive(
            try signedResponse(challenge: first, counter: 2),
            at: 2.02, via: .notification
        )) {
            XCTAssertEqual($0 as? DeviceProtocolV0.ProtocolError, .invalidSignature)
        }
        let valid = try signedResponse(challenge: second, counter: 3)
        _ = try session.receive(valid, at: 2.2, via: .readFallback)
        XCTAssertEqual(session.results.last?.transport, .readFallback)
        XCTAssertThrowsError(try session.beginChallenge(
            nonce: second.nonce, observationEpoch: 2, observationHint: hint, startedAt: 3
        )) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .reusedNonce)
        }
        _ = try session.beginChallenge(
            nonce: Data(repeating: 3, count: 32), observationEpoch: 2,
            observationHint: hint, startedAt: 3
        )
        let third = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 3, count: 32), observationEpoch: 2,
            observationHint: hint
        )
        _ = try session.receive(try signedResponse(challenge: third, counter: 4),
                                at: 3.3, via: .notification)
        XCTAssertNil(session.medianNotificationRTTMilliseconds)
    }

    func testTimeoutAndInterruptionRejectLateResponses() throws {
        let info = try DeviceProtocolV0.Info(wireData: infoData())
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 5, count: 32), observationEpoch: 0,
            observationHint: Data(repeating: 0, count: 8)
        )
        let response = try signedResponse(challenge: challenge, counter: 1)

        var timedOut = ChallengeSession(info: info)
        _ = try timedOut.beginChallenge(
            nonce: challenge.nonce, observationEpoch: 0,
            observationHint: challenge.observationHint, startedAt: 10
        )
        XCTAssertFalse(try timedOut.expirePending(at: 14.9, after: 5))
        XCTAssertTrue(try timedOut.expirePending(at: 15, after: 5))
        XCTAssertThrowsError(try timedOut.receive(response, at: 15.1, via: .notification)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .timedOut)
        }

        var interrupted = ChallengeSession(info: info)
        _ = try interrupted.beginChallenge(
            nonce: challenge.nonce, observationEpoch: 0,
            observationHint: challenge.observationHint, startedAt: 10
        )
        interrupted.interrupt()
        XCTAssertThrowsError(try interrupted.receive(response, at: 10.1, via: .notification)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .interrupted)
        }
        XCTAssertThrowsError(try interrupted.beginChallenge(
            nonce: Data(repeating: 6, count: 32), observationEpoch: 0,
            observationHint: challenge.observationHint, startedAt: 11
        )) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .interrupted)
        }
    }
}
