import CryptoKit
import Foundation
import PathnodChallengeCore
import XCTest

final class ChallengeCoreTests: XCTestCase {
    private let key = Curve25519.Signing.PrivateKey()

    private func hexData(_ hex: String) -> Data {
        Data(stride(from: 0, to: hex.count, by: 2).map {
            UInt8(hex.dropFirst($0).prefix(2), radix: 16)!
        })
    }

    private func infoData() -> Data {
        var data = Data([0, 1])
        data.append(key.publicKey.rawRepresentation)
        data.append(Data(repeating: 0, count: 36))
        return data
    }

    private func signedResponse(
        challenge: DeviceProtocolV0.Challenge,
        timestamp: UInt64 = 42,
        counter: UInt32
    ) throws -> Data {
        var message = Data("Pathnod/challenge/v0".utf8)
        message.append(challenge.wireData())
        message.append(contentsOf: bytes(timestamp))
        message.append(contentsOf: bytes(counter))
        message.append(Data(repeating: 0, count: 32))
        let signature = try key.signature(for: Data(SHA256.hash(data: message)))
        var response = signature
        response.append(contentsOf: bytes(timestamp))
        response.append(contentsOf: bytes(counter))
        response.append(contentsOf: [0, 0])
        XCTAssertEqual(DeviceProtocolV0.signedMessage(
            challenge: challenge, response: try DeviceProtocolV0.Response(wireData: response)
        ), message)
        return response
    }

    private func bytes<T: FixedWidthInteger>(_ value: T) -> [UInt8] {
        stride(from: T.bitWidth - 8, through: 0, by: -8).map {
            UInt8(truncatingIfNeeded: value >> $0)
        }
    }

    func testInfoValidationAndCanonicalChallenge() throws {
        let info = try DeviceProtocolV0.Info(wireData: infoData())
        XCTAssertEqual(info.publicKey, key.publicKey.rawRepresentation)
        XCTAssertEqual(info.capabilities, 0)
        XCTAssertEqual(info.protocolHint, Data(repeating: 0, count: 32))
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(0..<32), observationEpoch: 0x01020304,
            observationHint: Data(0xa0..<0xa8)
        )
        XCTAssertEqual(challenge.wireData().count, 44)
        XCTAssertEqual(Array(challenge.wireData()[32..<36]), [1, 2, 3, 4])
        XCTAssertEqual(DeviceProtocolV0.domain.count, 20)

        XCTAssertThrowsError(try DeviceProtocolV0.Info(wireData: infoData().dropLast()))
        var wrongVersion = infoData()
        wrongVersion[0] = 1
        XCTAssertThrowsError(try DeviceProtocolV0.Info(wireData: wrongVersion)) {
            XCTAssertEqual($0 as? DeviceProtocolV0.ProtocolError, .unsupportedDevice)
        }
        XCTAssertThrowsError(try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 0, count: 31), observationEpoch: 0,
            observationHint: Data(repeating: 0, count: 8)
        ))
    }

    func testDEV09InteroperabilityVector() throws {
        // Public interoperability vector generated by DEV-09.
        let info = try DeviceProtocolV0.Info(wireData: hexData(
            "0001ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c" +
            "000000000000000000000000000000000000000000000000000000000000000000000000"
        ))
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(0..<32), observationEpoch: 0,
            observationHint: Data(repeating: 0, count: 8)
        )
        let response = try DeviceProtocolV0.Response(wireData: hexData(
            "bb9541f0b1b8d273b230f1c7accbe941fbfb43cfedcc934486b0bd4feeb3e07" +
            "4470663c7bb14e4fae6411e0b40c2a95dce2421f42ae35d98df1fd188521b080e" +
            "000000000000002a000000010000"
        ))
        XCTAssertEqual(response.deviceTimestamp, 42)
        XCTAssertEqual(response.deviceCounter, 1)
        XCTAssertNoThrow(try DeviceProtocolV0.verify(
            response: response, challenge: challenge, info: info
        ))
    }

    func testResponseRejectsTruncationAndUnsupportedEvidence() throws {
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 1, count: 32), observationEpoch: 2,
            observationHint: Data(repeating: 3, count: 8)
        )
        let response = try signedResponse(challenge: challenge, counter: 1)
        XCTAssertEqual(response.count, 78)
        XCTAssertThrowsError(try DeviceProtocolV0.Response(wireData: response.dropLast()))
        var extra = response
        extra.append(9)
        XCTAssertThrowsError(try DeviceProtocolV0.Response(wireData: extra))
        extra[77] = 1
        XCTAssertThrowsError(try DeviceProtocolV0.Response(wireData: extra)) {
            XCTAssertEqual($0 as? DeviceProtocolV0.ProtocolError, .unsupportedEvidence)
        }
    }

    func testThreeSequentialVerifiedChallengesAndMedian() throws {
        var session = ChallengeSession(info: try .init(wireData: infoData()))
        for attempt in 1...3 {
            let nonce = Data(repeating: UInt8(attempt), count: 32)
            let wire = try session.beginChallenge(
                nonce: nonce, observationEpoch: 2,
                observationHint: Data(repeating: 0, count: 8),
                startedAt: Double(attempt * 3)
            )
            XCTAssertEqual(wire.count, 44)
            let challenge = try DeviceProtocolV0.Challenge(
                nonce: nonce, observationEpoch: 2,
                observationHint: Data(repeating: 0, count: 8)
            )
            let response = try signedResponse(challenge: challenge, counter: UInt32(attempt))
            guard case let .verified(result) = try session.receive(
                response, at: Double(attempt * 3) + Double(attempt) / 100,
                via: .notification
            ) else { return XCTFail("Expected a verified response") }
            XCTAssertEqual(result.attempt, attempt)
            XCTAssertEqual(result.roundTripMilliseconds, Double(attempt * 10), accuracy: 0.001)
        }
        XCTAssertTrue(session.isComplete)
        XCTAssertEqual(session.medianNotificationRTTMilliseconds!, 20, accuracy: 0.001)
        XCTAssertThrowsError(try session.beginChallenge(
            nonce: Data(repeating: 4, count: 32), observationEpoch: 2,
            observationHint: Data(repeating: 0, count: 8), startedAt: 12
        ))
    }

    func testStaleDuplicateAndMismatchedResponse() throws {
        var session = ChallengeSession(info: try .init(wireData: infoData()))
        let hint = Data(repeating: 0, count: 8)
        let first = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 1, count: 32), observationEpoch: 2,
            observationHint: hint
        )
        _ = try session.beginChallenge(nonce: first.nonce, observationEpoch: 2,
                                       observationHint: hint, startedAt: 3)
        let oldResponse = try signedResponse(challenge: first, counter: 1)
        _ = try session.receive(oldResponse, at: 3.1, via: .notification)

        let second = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 2, count: 32), observationEpoch: 2,
            observationHint: hint
        )
        _ = try session.beginChallenge(nonce: second.nonce, observationEpoch: 2,
                                       observationHint: hint, startedAt: 6)
        guard case .ignoredDuplicate = try session.receive(
            oldResponse, at: 6.01, via: .notification
        ) else { return XCTFail("Old response must be ignored") }
        XCTAssertEqual(session.results.count, 1)
        XCTAssertThrowsError(try session.receive(
            try signedResponse(challenge: first, counter: 2),
            at: 6.02, via: .notification
        )) {
            XCTAssertEqual($0 as? DeviceProtocolV0.ProtocolError, .invalidSignature)
        }
        let valid = try signedResponse(challenge: second, counter: 3)
        _ = try session.receive(valid, at: 6.2, via: .readFallback)
        XCTAssertEqual(session.results.last?.transport, .readFallback)
        XCTAssertThrowsError(try session.beginChallenge(
            nonce: second.nonce, observationEpoch: 2, observationHint: hint, startedAt: 9
        )) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .reusedNonce)
        }
        _ = try session.beginChallenge(
            nonce: Data(repeating: 3, count: 32), observationEpoch: 2,
            observationHint: hint, startedAt: 9
        )
        let third = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 3, count: 32), observationEpoch: 2,
            observationHint: hint
        )
        _ = try session.receive(try signedResponse(challenge: third, counter: 4),
                                at: 9.3, via: .notification)
        XCTAssertNil(session.medianNotificationRTTMilliseconds)
    }

    func testTimeoutAndInterruptionRejectLateResponses() throws {
        let info = try DeviceProtocolV0.Info(wireData: infoData())
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: 5, count: 32), observationEpoch: 0,
            observationHint: Data(repeating: 0, count: 8)
        )
        let response = try signedResponse(challenge: challenge, counter: 1)

        var timedOut = ChallengeSession(info: info)
        _ = try timedOut.beginChallenge(
            nonce: challenge.nonce, observationEpoch: 0,
            observationHint: challenge.observationHint, startedAt: 10
        )
        XCTAssertFalse(try timedOut.expirePending(at: 14.9, after: 5))
        XCTAssertTrue(try timedOut.expirePending(at: 15, after: 5))
        XCTAssertThrowsError(try timedOut.receive(response, at: 15.1, via: .notification)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .timedOut)
        }

        var interrupted = ChallengeSession(info: info)
        _ = try interrupted.beginChallenge(
            nonce: challenge.nonce, observationEpoch: 0,
            observationHint: challenge.observationHint, startedAt: 10
        )
        interrupted.interrupt()
        XCTAssertThrowsError(try interrupted.receive(response, at: 10.1, via: .notification)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .interrupted)
        }
        XCTAssertThrowsError(try interrupted.beginChallenge(
            nonce: Data(repeating: 6, count: 32), observationEpoch: 0,
            observationHint: challenge.observationHint, startedAt: 11
        )) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .interrupted)
        }
    }

    private func infoData(capabilities: UInt32) -> Data {
        var data = infoData()
        data.replaceSubrange(34..<38, with: bytes(capabilities))
        return data
    }

    private func run(
        _ session: inout ChallengeSession, nonce: UInt8, at time: Double, counter: UInt32
    ) throws -> ChallengeSession.Receipt {
        let hint = Data(repeating: 0, count: 8)
        _ = try session.beginChallenge(
            nonce: Data(repeating: nonce, count: 32), observationEpoch: 0,
            observationHint: hint, startedAt: time
        )
        let challenge = try DeviceProtocolV0.Challenge(
            nonce: Data(repeating: nonce, count: 32), observationEpoch: 0, observationHint: hint
        )
        return try session.receive(
            try signedResponse(challenge: challenge, counter: counter),
            at: time + 0.05, via: .notification
        )
    }

    func testChallengesArePacedForTheDeviceRateLimit() throws {
        var session = ChallengeSession(info: try .init(wireData: infoData()))
        XCTAssertNil(session.nextChallengeAllowedAt)
        XCTAssertEqual(ChallengeSession.defaultChallengeSpacingSeconds, 2.25, accuracy: 0.001)
        _ = try run(&session, nonce: 1, at: 10, counter: 1)
        XCTAssertEqual(session.nextChallengeAllowedAt!, 12.25, accuracy: 0.001)
        // The spacing is measured between writes, so the RTT does not count towards it.
        XCTAssertThrowsError(try run(&session, nonce: 2, at: 12.2, counter: 2)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .challengeTooSoon)
        }
        XCTAssertFalse(session.hasPendingChallenge)
        guard case let .verified(result) = try run(&session, nonce: 2, at: 12.25, counter: 2) else {
            return XCTFail("Expected a verified response")
        }
        XCTAssertEqual(result.roundTripMilliseconds, 50, accuracy: 0.001)
        XCTAssertEqual(session.nextChallengeAllowedAt!, 14.5, accuracy: 0.001)
        XCTAssertThrowsError(try run(&session, nonce: 3, at: 11, counter: 3)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .invalidClock)
        }
    }

    func testCounterMustIncreaseWhenTheDeviceClaimsIt() throws {
        // DEV-22 firmware: monotonic counter (bit 1) and rate limit (bit 3).
        let info = try DeviceProtocolV0.Info(wireData: infoData(capabilities: 0x0a))
        XCTAssertEqual(info.capabilitySet, [.monotonicCounter, .challengeRateLimit])
        XCTAssertEqual(info.capabilitySet.names, ["monotonic counter", "challenge rate limit"])

        var repeated = ChallengeSession(info: info)
        _ = try run(&repeated, nonce: 1, at: 0, counter: 65)
        XCTAssertThrowsError(try run(&repeated, nonce: 2, at: 3, counter: 65)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .nonIncreasingCounter)
        }
        XCTAssertEqual(repeated.results.count, 1)

        var lower = ChallengeSession(info: info)
        _ = try run(&lower, nonce: 1, at: 0, counter: 7)
        XCTAssertThrowsError(try run(&lower, nonce: 2, at: 3, counter: 6))

        var zero = ChallengeSession(info: info)
        XCTAssertThrowsError(try run(&zero, nonce: 1, at: 0, counter: 0)) {
            XCTAssertEqual($0 as? ChallengeSession.SessionError, .nonIncreasingCounter)
        }

        // Gaps are expected after a reboot or a reservation block boundary.
        var gaps = ChallengeSession(info: info)
        for (index, counter) in [UInt32(63), 64, 129].enumerated() {
            _ = try run(&gaps, nonce: UInt8(index + 1), at: Double(index * 3), counter: counter)
        }
        XCTAssertEqual(gaps.results.map(\.deviceCounter), [63, 64, 129])

        // Without capability bit 1 the counter is informational (macOS simulator).
        var simulator = ChallengeSession(info: try .init(wireData: infoData()))
        _ = try run(&simulator, nonce: 1, at: 0, counter: 5)
        _ = try run(&simulator, nonce: 2, at: 3, counter: 5)
        XCTAssertEqual(simulator.results.count, 2)
    }

    func testAdvertisedDeviceIDPrefixMatchesInfo() throws {
        let info = try DeviceProtocolV0.Info(wireData: infoData())
        let expected = Data(SHA256.hash(
            data: Data("Pathnod/device/v0".utf8) + key.publicKey.rawRepresentation
        ))
        XCTAssertEqual(DeviceProtocolV0.deviceIDDomain.count, 17)
        XCTAssertEqual(info.deviceID, expected)
        XCTAssertEqual(
            try DeviceProtocolV0.checkAdvertisedIdentity(serviceData: expected.prefix(8), info: info),
            .matched
        )
        XCTAssertEqual(
            try DeviceProtocolV0.checkAdvertisedIdentity(serviceData: nil, info: info),
            .notAdvertised
        )
        var altered = Data(expected.prefix(8))
        altered[7] ^= 1
        for serviceData in [altered, Data(expected.prefix(7)), Data(expected.prefix(9)), Data()] {
            XCTAssertThrowsError(try DeviceProtocolV0.checkAdvertisedIdentity(
                serviceData: serviceData, info: info
            )) {
                XCTAssertEqual($0 as? DeviceProtocolV0.ProtocolError, .deviceIDMismatch)
            }
        }
    }
}
