[package]
name = "pathnod"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Pathnod protocol registry and development observation verifier"

[lib]
crate-type = ["cdylib", "lib"]
name = "pathnod"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "anchor-spl/token_2022"]

[dependencies]
anchor-lang = { version = "=1.2.0", features = ["init-if-needed"] }
anchor-spl = { version = "=1.2.0", default-features = false, features = ["token"] }
groth16-solana = "=0.2.0"
solana-define-syscall = "=5.2.0"
solana-sha256-hasher = { version = "=3.1.0", features = ["sha2"] }
solana-instructions-sysvar = "=3.0.1"
solana-poseidon = "=5.0.0"

[dev-dependencies]
serde_json = "1"
