import CryptoKit
import XCTest
@testable import PathnodObservationCore

final class PayoutTests: XCTestCase {
    func testExpiredBlockhashAllowsReplacementWhileAuthorizationIsStillValid() throws {
        // Authorization still has 83 seconds remaining: transaction height, not
        // authorization time, determines whether the old wire can be replaced.
        let now: UInt64 = 2_000_000_000, authorizationExpiry = now + 83
        XCTAssertGreaterThan(authorizationExpiry, now)
        XCTAssertEqual(try WithdrawalRecovery.action(status:.absent,finalizedHeight:151,
            lastValidBlockHeight:150,savedNonce:0,finalizedNonce:0),.replace)
        XCTAssertEqual(try WithdrawalRecovery.action(status:.absent,finalizedHeight:150,
            lastValidBlockHeight:150,savedNonce:0,finalizedNonce:0),.retry)
    }
    func testLostResponseAndAmbiguousRecoveryCannotDuplicateWithdrawal() throws {
        XCTAssertEqual(try WithdrawalRecovery.action(status:.absent,finalizedHeight:151,
            lastValidBlockHeight:150,savedNonce:0,finalizedNonce:1),.completed)
        for transaction in [WithdrawalTransactionStatus.pending, .finalized] {
            XCTAssertEqual(try WithdrawalRecovery.action(status:transaction,finalizedHeight:151,
                lastValidBlockHeight:150,savedNonce:0,finalizedNonce:0),.wait)
        }
        XCTAssertEqual(try WithdrawalRecovery.action(status:.absent,finalizedHeight:151,
            lastValidBlockHeight:nil,savedNonce:0,finalizedNonce:0),.wait)
        XCTAssertThrowsError(try WithdrawalRecovery.action(status:.absent,finalizedHeight:151,
            lastValidBlockHeight:150,savedNonce:1,finalizedNonce:0))
    }
    func testFailedTransactionStillRequiresFinalizedExpiryBeforeReplacement() throws {
        XCTAssertEqual(try WithdrawalRecovery.action(status:.failed,finalizedHeight:150,
            lastValidBlockHeight:150,savedNonce:0,finalizedNonce:0),.wait)
        XCTAssertEqual(try WithdrawalRecovery.action(status:.failed,finalizedHeight:151,
            lastValidBlockHeight:150,savedNonce:0,finalizedNonce:0),.replace)
    }
    func testSDKClaimMessageAndRejectArbitrarySigning() throws {
        // Public deterministic test seeds only; message generated by @pathnod/solana.
        let authorization = try JSONDecoder().decode(PayoutAuthorization.self, from: Data(#"{"program":"CktRuQ2mttgRGkXJtyksdKHjUdc2C4TgDzyB98oEzy8","payout":"AGGT4SQQbdH7yYTpYb485EfqnxkcbHceVTrgqJx58EsQ","mint":"4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU","withdrawalKey":"AKnL4NNf3DGWZJS6cPknBuEGnVsV4A4m5tgebLHaRSZ9","destination":"QWmroo4YnnMqYW3cnxWkFdaTxGD3P7vMSzwMHGbUzwF","amount":"40000","nonce":"0","expiresAt":"2000000000","policyVersion":1}"#.utf8))
        let verifier="9hSR6S7WPtxmTojgo6GG3k4yDPecgJY292j7xrsUGWBu"
        let signature=Data(base64Encoded:"Z89DUUoTwxVSLIh8d/VIPNPTdnUVKCXBVmGpafta60UpbT/bzb1gz2/t0n6QXRKXpxIjKMMUh6q8AN98/EBeDA==")!
        let message=Data(base64Encoded:"AQAGCoqI4910CfGV/VLbLTy6XXLKZwm/HZQSG/N0iAG0D29ciaJc8NmHq5AQrW6VYjLNTACoXoAgE6ckwGcdkw6uYjfBkv2loOsep9ajk+15I9R8YtGOZEy9aunUbLOf0vpDzgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGO0Qss5EhV/E6kz0BNCgtAytf/s0Botvxt3kGCN8ALqdrI8sf+mi/TfICId+Bs+4Y+aX2BjsREaXqyxN9Gy5+sQMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA31G1nyT+74S+UKPg41A/wVwdEkn9Ipk/MpwRIAAAAAGp9UXGHvRZjXa1ARV/cLAwSTGjyFWdaXbustfCAAAAAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcCBwCQAQEAMAD//xAA//9wACAA//+BOXcOqH0XX1ajVGbDTH7My42KkbTuN6Jd9g9bj8mzlGfPQ1FKE8MVUiyIfHf1SDzT03Z1FSglwVZhqWn7WutFKW0/2829YM9v7dJ+kF0Sl6cSIyjDFIeqvADffPxAXgyn2p73IiKYbKuAhebDsT+zNFRLwEArvCVNpKN49EzeiQYIBQEEAgMACAkgf/CEPuPGkoVAnAAAAAAAAAAAAAAAAAAAAJQ1dwAAAAA=")!
        let key=try Curve25519.Signing.PrivateKey(rawRepresentation:Data(repeating:1,count:32))
        XCTAssertEqual(try authorization.digest().map {String(format:"%02x",$0)}.joined(),"a7da9ef72222986cab8085e6c3b13fb334544bc0402bbc254da4a378f44cde89")
        let sign: (Data,UInt64) throws -> Data = { try authorization.signedWire(message:$0,verifier:verifier,signature:signature,privateKey:key,expectedProgram:authorization.program,now:$1) }
        let wire=try sign(message,1_999_999_900)
        XCTAssertTrue(key.publicKey.isValidSignature(Data(wire[1..<65]),for:message))
        for offset in [0,3,36,message.count-1] {
            var altered=message; altered[offset] ^= 1
            XCTAssertThrowsError(try sign(altered,1_999_999_900))
        }
        XCTAssertThrowsError(try sign(message+Data([0]),1_999_999_900))
        XCTAssertThrowsError(try sign(message,2_000_000_001))
    }
    func testBase58AndIntegerAmounts() throws {
        for key in [Data(repeating: 0, count: 32), Data(repeating: 255, count: 32), Curve25519.Signing.PrivateKey().publicKey.rawRepresentation] {
            XCTAssertEqual(try SolanaBase58.decode32(SolanaBase58.encode(key)), key)
        }
        XCTAssertEqual(try PayoutBalance.baseUnits("0.040000"), 40_000)
        XCTAssertEqual(try PayoutBalance.baseUnits("18446744073709.551615"), UInt64.max)
        for amount in ["1.2", "-1.000000", "18446744073709.551616", "0.nan000"] {
            XCTAssertThrowsError(try PayoutBalance.baseUnits(amount))
        }
        XCTAssertThrowsError(try SolanaBase58.decode32("0"))
        XCTAssertThrowsError(try SolanaBase58.decode32(String(repeating: "1", count: 33)))
    }
}
